apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: forgejo-runner
resources:
  - namespace.yaml

# --------------------------------------------
# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization

# components:
# - ../../../../base/apps/forgejo-runner

# helmCharts:
# - name: forgejo-runner
#   namespace: forgejo-runner
#   version: 0.6.6
#   repo: oci://codeberg.org/wrenix/helm-charts/
#   valuesFile: ../../../../base/apps/forgejo-runner/values.yaml
#   releaseName: ""
#   valuesInline:
#      fullnameOverride: forgejo-runner
#   includeCRDs: true
