apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- ../../../../base/apps/gitlab-runner

helmCharts:
- name: gitlab-runner
  namespace: gitlab-runner
  version: 0.83.3
  repo: https://charts.gitlab.io/
  valuesFile: ../../../../base/apps/gitlab-runner/values.yaml
  releaseName: ""
  valuesInline:
     fullnameOverride: gitlab-runner
  includeCRDs: true
